import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Todos from "../src/components/Todos/Todos";
import { useAuth } from "../src/Hooks/useAuth";
import Login from "../src/components/Login/Login";
import Lists from "../src/components/Lists/Lists";
const Home: NextPage = () => {
  const currentUser: User = useAuth();

  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {currentUser.email ? (
          <div className="flex flex-col items-center">
            <Lists></Lists>
            {/* <Todos></Todos> */}
          </div>
        ) : (
          <div>
            <header className={styles.header}>Next.js Todo List</header>
            <Login />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
